### ISSUE TITLE
Airline theme doesn't use the jay colour palette

### ISSUE THREAD

**Issue by tjbcg** [josuegaleas/jay#2]
![scrennshot](http://i.imgur.com/rCTBOcM.png)

Airline and the buffer line both don't use the jay colour palette.
I purposedly modified the content of the right window, to show the red colour (`#D70000`, instead of `#DF5F5F` or `#D75F5F`).

That makes vim really aggressive, and almost unusable for more than an hour.

N.B. : I have set the airline theme to jay, using both `let g:airline_theme='jay'` and `:AirlineTheme jay`, and this is the theme. 

Is this the expected behavior (thus a matter of taste), or an issue with the colourscheme ?

**Comment by josuegaleas** [comment]
Ah, I think I see what the problem is. Do you have [vim-airline-themes](https://github.com/vim-airline/vim-airline-themes) installed? That repo had an old version of the Airline theme with a different color palette (which is what you see). Chris just accepted my [pull request](https://github.com/vim-airline/vim-airline-themes/commit/e03e9f62d25f9afb04c88ec6ca66cf2098242016) earlier today for the removal of the old Airline theme. The Airline theme is now in this repo, and it has the updated palette. Try and pull the latest changes from vim-airline-themes, since it seems like Vim is prioritizing the old Airline theme over the new, updated one. I hope this helps!

**Comment by tjbcg** [comment]
Yup, worked ! Thanks !
